addReviewers: true

addAssignees: true

reviewers:
  - MoegirlPediaInterfaceAdmins/bureaucrat
  - MoegirlPediaInterfaceAdmins/sysop

numberOfReviewers: 0

assignees:
  - MoegirlPediaInterfaceAdmins/bureaucrat
  - MoegirlPediaInterfaceAdmins/sysop

numberOfAssignees: 0
