default: true

# MD007/ul-indent - Unordered list indentation
MD007:
  # Spaces for indent
  indent: 4

# MD013/line-length - Line length
MD013: false

# MD033/no-inline-html - Inline HTML
MD033:
  # Allowed elements
  allowed_elements:
    - details
    - summary
