map: false

plugins:
  autoprefixer: {}
  postcss-selector-not: {}
  postcss-selector-matches: {}
  "@csstools/postcss-is-pseudo-class":
    specificityMatchingName: GaiBuHuiZhenYouRenYongZheGeClassBa
  postcss-font-variant: {}
  postcss-discard-comments: {}
  postcss-logical: {}
  "@csstools/postcss-media-minmax": {}
