name: linter test

description: linter test

inputs:
  commits:
    description: "commits json, only for postCommit"
    required: false

branding:
  icon: type
  color: purple

runs:
  using: composite
  steps:
    - name: Reload the cache
      uses: actions/cache@v3
      with:
        path: .cache
        key: cache@${{ github.ref }}
    - name: Check eslint environment
      run: npx eslint --env-info && mkdir -p .cache && echo ---- && ls -lhA .cache
      shell: bash
    - name: Run eslint
      run: npx eslint --exit-on-fatal-error --max-warnings 0 --cache --cache-strategy content --cache-location ".cache/" --ext js ./src
      shell: bash
    - name: Run stylelint
      run: npx stylelint --max-warnings 0 --cache --cache-strategy content --cache-location ".cache/" "src/**/*.css"
      shell: bash
    - name: Run v8r
      run: npx v8r
      shell: bash
    - name: Check .mailmap
      run: node scripts/emailmapChecker/index.js
      shell: bash
