name: linter test

description: linter test

inputs:
  commits:
    description: "commits json, only for postCommit"
    required: false

branding:
  icon: type
  color: purple

runs:
  using: composite
  steps:
    - name: Reload the cache
      uses: actions/cache@v3
      with:
        path: .cache
        key: cache@${{ github.ref }}
    - name: Check eslint environment
      run: npx eslint --env-info && mkdir -p .cache && echo ---- && ls -lhA .cache
      shell: bash
    - name: Run eslint
      run: npx eslint --exit-on-fatal-error --max-warnings 0 --cache --cache-strategy content --cache-location ".cache/" --ext js ./src
      shell: bash
    - name: Run stylelint
      run: npx stylelint --max-warnings 0 --cache --cache-strategy content --cache-location ".cache/" "src/**/*.css"
      shell: bash
    - name: Run v8r
      run: echo "::group::v8r output" && npx v8r && echo "::endgroup::"
      shell: bash
    - name: Check .mailmap
      run: node scripts/emailmapChecker/index.js
      shell: bash
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript
        config-file: ./.github/codeql-config.yml
    - name: Check ref and sha
      run: 'echo "Github context:" && echo "    ref: ${{ github.ref }}" && echo "    sha: ${{ github.sha }}" && echo "env:" && echo "   ref: $GITHUB_REF" && echo "   sha: $GITHUB_SHA"'
      shell: bash
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
