name: "Auto Assign"
on:
  pull_request_target:
    types:
      - opened
      - ready_for_review

env:
  GH_TOKEN: ${{ github.token }}

permissions: write-all

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: add assignees and reviewers
        run: |
          node scripts/test/test.js
