name: Linter test

on:
  push:
    branches: [master]
    paths:
      - "src/**"
      - ".github/workflows/Linter test.yml"
  pull_request:
    branches: [master]
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Reload the cache of eslint
        uses: actions/cache@v3
        with:
          path: .eslintcache
          key: eslintcache
      - name: Check eslint environment
        run: npx eslint --env-info && ls -lhA
      - uses: technote-space/get-diff-action@v6
        name: List diff
      - name: Run the linter
        run: npx eslint --exit-on-fatal-error --max-warnings 0 --cache --cache-strategy content --ext js ./src
