name: Linter test

on:
  push:
    branches: [master]
    paths:
      - "src/**/*.js"
      - "src/**/*.css"
      - "src/**/definition.json"
      - ".github/workflows/Linter test.yml"
  pull_request:
    branches: [master]
    paths:
      - "src/**/*.js"
      - "src/**/*.css"
      - "src/**/definition.json"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Reload the cache
        uses: actions/cache@v3
        with:
          path: .cache
          key: cache
      - name: Check eslint environment
        run: npx eslint --env-info && ls -lhA
      - uses: technote-space/get-diff-action@v6
        name: List diff
      - name: Run eslint
        run: npx eslint --exit-on-fatal-error --max-warnings 0 --cache --cache-strategy content --cache-location ".cache/" --ext js ./src
      - name: Run stylelint
        run: npx stylelint --max-warnings 0 --cache --cache-location ".cache/" "src/**/*.css"
      - name: Run v8r
        run: npx -y v8r@latest src/**/definition.json --schema .vscode/json-schemas/gadget-definition.json
