name: Linter test

on:
  push:
    paths:
      - src/**/*.js
      - src/**/*.css
      - src/**/definition.json
      - src/gadgets/Gadgets-definition-list.json
      - .github/workflows/Linter test.yml
  pull_request:
    paths:
      - src/**/*.js
      - src/**/*.css
      - src/**/definition.json
  workflow_dispatch:
    inputs:
      from:
        description: Don't use this input manually
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Reload the cache
        uses: actions/cache@v3
        with:
          path: .cache
          key: cache
      - uses: technote-space/get-diff-action@v6
        name: List diff
      - name: Run actions
        run: node scripts/workflows/linterTest.js
      - name: Trigger post commit CI
        if: inputs.from != 'postCommit' && github.event_name == 'push'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'postCommit.yml',
              ref: context.ref,
            })
