name: post commit CI

on:
  push:
    paths:
      - "scripts/**/*.js"
      - ".github/workflows/postCommit.yml"
  workflow_dispatch:
  schedule:
    - cron: 15 0 * * *

concurrency: postCommit

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  actions: write
  checks: read
  contents: write
  deployments: read
  id-token: read
  issues: write
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  postCommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - name: "Prepare: Install dependencies"
        run: npm ci
      - name: "Prepare: Prepare git"
        run: node scripts/postCommit/prepareGit.js
      - name: "Prepare: Expose GitHub Runtime"
        uses: crazy-max/ghaction-github-runtime@v2
      - name: Auto browserify generator
        run: node scripts/browserify/index.js
      - name: Auto prefetch
        run: node scripts/prefetch/index.js
      - name: Gadget-polyfill generator
        run: node scripts/generatePolyfill/index.js
      - name: Gadgets-definition Generator
        run: node scripts/gadgetsDefinitionGenerator/index.js
      - name: Conventional Commits scopes generator
        run: node scripts/conventionalCommitsScopesGenerator/index.js
      - name: linguist-generated to .gitattributes
        run: node scripts/postCommit/linguist-generated.js
      - name: Show git status & push
        run: node scripts/postCommit/push.js
