name: post commit CI

on:
  push:
    paths:
      - scripts/**/*.js
      - "!scripts/test/*.js"
      - src/**/*.js
      - src/**/*.css
      - src/**/definition.yaml
      - src/gadgets/Gadgets-definition-list.yaml
      - .github/workflows/postCommit.yml
      - .github/workflows/Linter test.yml
      - .github/linter test/action.yaml
      - .vscode/json-schemas/gadget-definition.json
      - .browserslistrc
      - .*.yaml
      - package-lock.json
  workflow_dispatch:
  schedule:
    - cron: 15 0 * * *

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: write
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: write
  statuses: read

jobs:
  postCommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 7
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - name: "Prepare: Install dependencies"
        run: npm run ci
      - name: "Prepare: Git config"
        run: node scripts/postCommit/prepareGit.js
      - name: "Prepare: Expose GitHub Runtime"
        uses: crazy-max/ghaction-github-runtime@v2
      - name: Auto browserify generator
        run: node scripts/browserify/index.js
      - name: Auto prefetch
        run: node scripts/prefetch/index.js
      - name: Gadget-polyfill generator
        run: node scripts/generatePolyfill/index.js
      - name: Gadgets-definition Generator
        run: node scripts/gadgetsDefinitionGenerator/index.js
      - name: Conventional Commits scopes generator
        run: node scripts/conventionalCommitsScopesGenerator/index.js
      - name: linguist-generated
        run: node scripts/postCommit/linguist-generated.js
      - name: Show git status & push
        run: node scripts/postCommit/push.js
      - name: Run linter test # Name MUST NOT be changed.
        uses: ./.github/linter test
        if: ${{ env.linterTest == 'true' }}
