name: test

on:
  push:
    branches: [master]
    paths:
      - "src/**"
  pull_request:
    branches: [master]
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - name: Install eslint
        run: npm install --location=global eslint@latest
      - name: Check eslint installation
        run: npx eslint --env-info
      - name: Reload the cache of eslint
        uses: actions/cache@v3
        with:
          path: .eslintcache
          key: eslint
      - name: Check the linter
        run: npx eslint --exit-on-fatal-error --max-warnings 0 --cache --cache-strategy content --ext js ./src
