name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "npm"
      - run: npm install eslint@latest -g
      - run: npx eslint --env-info
      - run: npx eslint --exit-on-fatal-error --ext js ./src
