name: test

on:
  push:
    branches: [master]
    paths:
      - "src/**"
  pull_request:
    branches: [master]
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "npm"
      - run: npm install --location=global eslint@latest
      - run: npx eslint --env-info
      - run: npx eslint --exit-on-fatal-error --max-warnings 0  --ext js ./src
